### ISSUE TITLE
Fatal error , failed to connect to local steam client 

### ISSUE THREAD

**Issue by srihari-humbarwadi** [arno01/steam#24]
I get this error when launching some half life games with
the scale option
"Fatal error: failed to connect to local steam client"
Steam beta : No
Distro : ubuntu 16.04
Gpu : gtx 1060
How to reproduce 
1 ```docker-compose scale steam=2```
2 Then try launching the game in second container

**Comment by arno01** [comment]
Hi @srihari-humbarwadi !

The error you are getting is because "scale" command would create an additional Steam instance, using the same local data.
Please do not use "scale" command.

If you want to run multiple instances of Steam, please make sure you provide different local mount points e.g. ``./data1``, ``./data2``, ``./data3`` ... (in your host) to the ``/home/user`` (in container).

And this docker image was not meant nor tested for running multiple Steam instances.

**Comment by srihari-humbarwadi** [comment]
@arno01 if i wanted to use scale command with a single mount point how should i approach it , is there anything that i can try to tweak in the launch file ?

**Comment by arno01** [comment]
@srihari-humbarwadi not really, if the Steam writes to the same state files, then every additional Steam instance is going to read the same state files and see that it is already running, thus giving you ``Fatal error: failed to connect to local steam client`` error.

Then, even if you happen to trick the PID namespace and manage to run more than 1 Steam instance using the same data, there is a high chance you will fall into a "split-brain" scenario where Steam will start corrupting its data.

So the only way is to make multiple copies of the ``data`` directory.

**Comment by srihari-humbarwadi** [comment]
@arno01 Okay ill go with multiple mounts point for /home/$USER. But i notices that each steam instance acquires only a  shared lock on the game files , so is it possible for the instances to share common game files and have separate steam folders?This would prevent redundant copies of the game (15gb !)

**Comment by arno01** [comment]
Go ahead and give it a try! Just specify the proper mount points in the docker-compose file. And only one Steam instance should be allowing automatic game updates. Additionally, you can add ``:ro`` at the game datw mountpoint so that way Docker will not allow any writes to that directory. Though, this may break things.

Let me know if that works for you.

## quick tip

If you do not want to waste the disk space for multiple copies of the same data, you can use ZFS with the data deduplication enabled for your mountpoint where you want to keep multiple copies of the same data. ;-)

The only minus is that ZFS eats more RAM.
There are few more fipe systems which allow data deduplication. (do not mix it with the data compression)

**Comment by srihari-humbarwadi** [comment]
@arno01 
I mounted ./data1, ./data2, ./data3 ( host) to the /home/user (container)
Now how to map ./data1 to instance1 ./data2 to instance2;ie how i use scale command now
Quick update -  i got the steam instances access a game files directory by keeping it in /opt/steamgames
